### ISSUE TITLE
Pi Zero 2 W TV out setup

### ISSUE THREAD

**Issue by gavan-x** [astefanutti/kms-glsl#16]
Outputting to composite out.
`dtoverlay=vc4-fkms-v3d `

kmscube works but I just get a similar output with most examples.
![image](https://github.com/astefanutti/kms-glsl/assets/40079787/e6a89054-6497-4a10-82b0-aba6c0ce6702)

**Comment by astefanutti** [comment]
Could you try with `dtoverlay=vc4-fkms-v3d,composite` as suggested in https://github.com/astefanutti/kms-glsl/issues/7#issuecomment-1426575570?

**Comment by gavan-x** [comment]
Tried that as well as with ...,composite=1

Same output
FYI glxinfo can't open display but kmscube runs.

**Comment by astefanutti** [comment]
Could you please give me the output for `kmscube`?

Unfortunately I don't have a composite TV to test it myself.

**Comment by gavan-x** [comment]
Program runs with a spinning cube.
What command should I run for the output you need?

**Comment by astefanutti** [comment]
> What command should I run for the output you need?

I meant the info printed in the console after you run kmscube, that give the display info and EGL / OpenGL versions.

**Comment by gavan-x** [comment]
Ahh yes I didn't realize that was the output right before the cube is displayed. Sorry I can't scroll up with this setup.![image](https://github.com/astefanutti/kms-glsl/assets/40079787/c29bd8dd-466e-410a-8a82-ad91afa274aa)

"10 (Buster)"
5.10.103-v8+

**Comment by astefanutti** [comment]
Thanks. Could you please try to rebuild kms-glsl from commit 99510608a4fa3306460d3922befb6d4e4a34674f, and run that version?

**Comment by gavan-x** [comment]
Works from that commit.

**Comment by astefanutti** [comment]
Great!

Can I ask you to test with commit 56e93d75fac6bfecae7d41976885ebc433ad83db? Sorry for the bisection, I wish I could test it locally, but that would help a lot to pinpoint the issue if you could give it another test 🙏🏼.

**Comment by astefanutti** [comment]
I finally got some time to look at it closely.

This should be fixed with #17.

Thanks for your patience.
