### ISSUE TITLE
switching the output to the second hdmi port?

### ISSUE THREAD

**Issue by markus2marks** [astefanutti/kms-glsl#4]
Hello,

I am using two displays, each connected to an HDMI port from my RPI CM4. But the program is only displayed on HDMI port 0. Is it possible to show the output on the second HDMI port? What do I have to change in the code for this or is it possible at all?

**Comment by astefanutti** [comment]
Maybe that's possible with the `--device` option, .e.g. `-D /dev/dri/...`, using the DRM device that corresponds to your second HDMI display.

**Comment by markus2marks** [comment]
That was my idea too, but it doesn't work. I always get an error message when I access dev/dri/card1.

**Comment by astefanutti** [comment]
What's the output of `ls /sys/class/drm`?

**Comment by markus2marks** [comment]
![grafik](https://user-images.githubusercontent.com/41025857/196797060-5850ca25-e834-47b8-9d91-84a954afefe0.png)

**Comment by markus2marks** [comment]
Thanks for your help, I found the solution :)

**Comment by astefanutti** [comment]
Great, let me close this 👍🏼.
